import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Fix component props type
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
